name: triviaapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^4.0.2
  flutter_bloc: ^6.0.0
  equatable: ^1.2.2
  dartz: ^0.9.1
  connectivity: ^0.4.9
  http: ^0.12.2
  shared_preferences: ^0.5.8
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:

  uses-material-design: true

